"""Публичные контакты для сайта и генераторов лендингов."""

# Личный контакт для сообщений
TELEGRAM_CONTACT_USERNAME = "maxima_com"
TELEGRAM_CONTACT_URL = f"https://t.me/{TELEGRAM_CONTACT_USERNAME}"
TELEGRAM_CONTACT_HANDLE = f"@{TELEGRAM_CONTACT_USERNAME}"

# Публичный канал
TELEGRAM_CHANNEL_USERNAME = "maxima_cfo"
TELEGRAM_CHANNEL_URL = f"https://t.me/{TELEGRAM_CHANNEL_USERNAME}"
TELEGRAM_CHANNEL_HANDLE = "@maxima-cfo"

# Обратная совместимость имён в генераторах
TELEGRAM_PUBLIC_USERNAME = TELEGRAM_CONTACT_USERNAME
TELEGRAM_PUBLIC_URL = TELEGRAM_CONTACT_URL
TELEGRAM_PUBLIC_HANDLE = TELEGRAM_CONTACT_HANDLE

PHONE_E164 = "+79808488480"
PHONE_TEL = f"tel:{PHONE_E164}"
PHONE_DISPLAY = "+7 980 848-84-80"
